services:
  courses-api:
    build: ./api/courses_api
    container_name: courses-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://courses-api-db:5432/courses-api-db
      SPRING_DATASOURCE_USERNAME: courses-api-db
      SPRING_DATASOURCE_PASSWORD: courses-api-db
    networks:
      - eduplus-network
    ports:
      - "8080:8080"
    depends_on:
      - courses-api-db
  
  comments-api:
    build: ./api/comments_api
    container_name: comments-api
    restart: always
    environment:
      SPRING_DATA_MONGODB_HOST: comments-api-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: comments-api-db
      SPRING_DATA_MONGODB_USERNAME: comments-api-db
      SPRING_DATA_MONGODB_PASSWORD: comments-api-db
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: admin
      COURSES_API_URL: http://courses-api:8080
      SERVER_PORT: 8081
    networks:
      - eduplus-network
    ports:
      - "8081:8081"
    depends_on:
      - comments-api-db

  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    restart: always
    environment:
      COURSES_API_URL: http://courses-api:8080
      COMMENTS_API_URL: http://comments-api:8081
      SERVER_PORT: 9000
    networks:
      - eduplus-network
    ports:
      - "9000:9000"
  
  courses:
    build: ./api/Courses
    container_name: courses
    restart: always
    environment:
      ASPNETCORE_HTTP_PORTS: 8082
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - eduplus-network
    ports:
      - "8082:8082"
    depends_on:
      - courses-db
  
  comments:
    build: ./api/Comments
    container_name: comments
    restart: always
    environment:
      ASPNETCORE_HTTP_PORTS: 8083
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - eduplus-network
    ports:
      - "8083:8083"
  
  courses-api-db:
    image: postgres
    container_name: courses-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-api-db
      POSTGRES_PASSWORD: courses-api-db
    volumes:
      - courses-api-data:/var/lib/postgresql/data
    networks:
      - eduplus-network
    ports:
      - "5432:5432"

  comments-api-db:
    image: mongo
    container_name: comments-api-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: comments-api-db
      MONGO_INITDB_ROOT_PASSWORD: comments-api-db
      MONGO_INITDB_DATABASE: comments-api-db
    volumes:
      - comments-api-data:/data/db
    networks:
      - eduplus-network
    ports:
      - "27017:27017"

  courses-db:
    image: postgres
    container_name: courses-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-db
      POSTGRES_PASSWORD: courses-db
    volumes:
      - courses-data:/var/lib/postgresql/data
    networks:
      - eduplus-network
    ports:
      - "5433:5432"

volumes:
  courses-api-data:
    name: courses-api-data
  comments-api-data:
    name: comments-api-data
  courses-data:
    name: courses-data

networks:
  eduplus-network:
    name: eduplus-network