services:
  comments-api-db:
    image: postgres
    container_name: comments-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-api-db
      POSTGRES_PASSWORD: comments-api-db
    volumes:
      - comments-api-data:/var/lib/postgresql/data
    networks:
      - comments-api-network
    ports:
      - "5432:5432"

  Comments-api-db:
    image: postgres
    container_name: Comments-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: Comments-api-db
      POSTGRES_PASSWORD: Comments-api-db
    volumes:
      - Comments-api-data:/var/lib/postgresql/data
      - ./Comments.api/DAL/Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - Comments-api-network
    ports:
      - "5433:5432"

  courses-api-db:
    image: postgres
    container_name: courses-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-api-db
      POSTGRES_PASSWORD: courses-api-db
    volumes:
      - courses-api-data:/var/lib/postgresql/data
    networks:
      - courses-api-network
    ports:
      - "5434:5432"
  
  Courses-api-db:
    image: postgres
    container_name: Courses-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: Courses-api-db
      POSTGRES_PASSWORD: Courses-api-db
    volumes:
      - Courses-api-data:/var/lib/postgresql/data
    networks:
      - Courses-api-network
    ports:
      - "5435:5432"

volumes:
  comments-api-data:
    name: comments-api-data
  Comments-api-data:
    name: Comments-api-data
  courses-api-data:
    name: courses-api-data
  Courses-api-data:
    name: Courses-api-data

networks:
  comments-api-network:
    name: comments-api-network
  Comments-api-network:
    name: Comments-api-network
  courses-api-network:
    name: courses-api-network
  Courses-api-network:
    name: Courses-api-network