services:
  comments-db-c#:
    image: postgres
    container_name: comments-db-c#
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-db-c#
      POSTGRES_PASSWORD: comments-db-c#
    volumes:
      - comments-data-c#:/var/lib/postgresql/data
    networks:
      - comments-network-c#
    ports:
      - "5432:5432"
  comments-db-java:
    image: postgres
    container_name: comments-db-java
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-db-java
      POSTGRES_PASSWORD: comments-db-java
    volumes:
      - comments-data-java:/var/lib/postgresql/data
    networks:
      - comments-network-java
    ports:
      - "5433:5432"

volumes:
  comments-data-c#:
    name: comments-data-c#
  comments-data-java:
    name: comments-data-java

networks:
  comments-network-c#:
    name: comments-network-c#
  comments-network-java:
    name: comments-network-java