services:
  comments-api-db-java:
    image: postgres
    container_name: comments-api-db-java
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-api-db-java
      POSTGRES_PASSWORD: comments-api-db-java
    volumes:
      - comments-api-data-java:/var/lib/postgresql/data
    networks:
      - comments-api-network-java
    ports:
      - "5432:5432"

  comments-api-db-csharp:
    image: postgres
    container_name: comments-api-db-csharp
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-api-db-csharp
      POSTGRES_PASSWORD: comments-api-db-csharp
    volumes:
      - comments-api-data-csharp:/var/lib/postgresql/data
      - ./comments_api_csharp/DAL/Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - comments-api-network-csharp
    ports:
      - "5433:5432"

  courses-api-db-java:
    image: postgres
    container_name: courses-api-db-java
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-api-db-java
      POSTGRES_PASSWORD: courses-api-db-java
    volumes:
      - courses-api-data-java:/var/lib/postgresql/data
    networks:
      - courses-api-network-java
    ports:
      - "5434:5432"
  
  courses-api-db-csharp:
    image: postgres
    container_name: courses-api-db-csharp
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-api-db-csharp
      POSTGRES_PASSWORD: courses-api-db-csharp
    volumes:
      - courses-api-data-csharp:/var/lib/postgresql/data
    networks:
      - courses-api-network-csharp
    ports:
      - "5435:5432"

volumes:
  comments-api-data-java:
    name: comments-api-data-java
  comments-api-data-csharp:
    name: comments-api-data-csharp
  courses-api-data-java:
    name: courses-api-data-java
  courses-api-data-csharp:
    name: courses-api-data-csharp

networks:
  comments-api-network-java:
    name: comments-api-network-java
  comments-api-network-csharp:
    name: comments-api-network-csharp
  courses-api-network-java:
    name: courses-api-network-java
  courses-api-network-csharp:
    name: courses-api-network-csharp