services:
  courses-db:
    image: postgres
    container_name: courses-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-db
      POSTGRES_PASSWORD: courses-db
    volumes:
      - courses-data:/var/lib/postgresql/data
      - ./Courses/DAL/Data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - courses-network
    ports:
      - "5432:5432"
  tasks-db:
    image: postgres:14
    container_name: tasks-db
    restart: always
    environment:
      POSTGRES_USER: tasks-db
      POSTGRES_PASSWORD: tasks-db
    volumes:
      - tasks-data:/var/lib/postgresql/data
    networks:
      - tasks-network
    ports:
      - "5433:5433"

volumes:
  courses-data:
    name: courses-data
  tasks-data:
    name: tasks-data

networks:
  courses-network:
    name: curses-network
  tasks-network:
    name: tasks-network