services:
  comments-db-java:
    image: postgres
    container_name: comments-db-java
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-db-java
      POSTGRES_PASSWORD: comments-db-java
    volumes:
      - comments-data:/var/lib/postgresql/data
    networks:
      - comments-network
    ports:
      - "5432:5432"

  comments-db-csharp:
    image: postgres
    container_name: comments-db-csharp
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: comments-db-csharp
      POSTGRES_PASSWORD: comments-db-csharp
    volumes:
      - comments-data:/var/lib/postgresql/data
    networks:
      - comments-network
    ports:
      - "5433:5432"

  courses-db-java:
    image: postgres
    container_name: courses-db-java
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-db-java
      POSTGRES_PASSWORD: courses-db-java
    volumes:
      - courses-data:/var/lib/postgresql/data
    networks:
      - courses-network
    ports:
      - "5434:5432"
  
  courses-db-csharp:
    image: postgres
    container_name: courses-db-csharp
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-db-csharp
      POSTGRES_PASSWORD: courses-db-csharp
    volumes:
      - courses-data:/var/lib/postgresql/data
    networks:
      - courses-network
    ports:
      - "5435:5432"

volumes:
  comments-data-java:
    name: comments-data-java
  comments-data-csharp:
    name: comments-data-csharp
  courses-data-java:
    name: courses-data-java
  courses-data-csharp:
    name: courses-data-csharp

networks:
  comments-network-java:
    name: comments-network-java
  comments-network-csharp:
    name: comments-network-csharp
  courses-network-java:
    name: courses-network-java
  courses-network-csharp:
    name: courses-network-csharp