services:
  Courses-db:
    image: postgres
    container_name: Courses-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: Courses-db
      POSTGRES_PASSWORD: Courses-db
    volumes:
      - Courses-data:/var/lib/postgresql/data
    networks:
      - Courses-network
    ports:
      - "5432:5432"
  
  courses-api-db:
    image: postgres
    container_name: courses-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: courses-api-db
      POSTGRES_PASSWORD: courses-api-db
    volumes:
      - courses-api-data:/var/lib/postgresql/data
    networks:
      - courses-api-network
    ports:
      - "5433:5432"

volumes:
  Courses-data:
    name: Courses-data
  courses-api-data:
    name: courses-api-data

networks:
  Courses-network:
    name: Courses-network
  courses-api-network:
    name: courses-api-network