services:
  Courses-db:
    image: postgres
    container_name: Courses-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - Courses-data:/var/lib/postgresql/data
    networks:
      - Courses-network
    ports:
      - "5432:5432"
  
  courses-api-db:
    image: postgres
    container_name: courses-api-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - courses-api-data:/var/lib/postgresql/data
    networks:
      - courses-api-network
    ports:
      - "5433:5432"
  
  comments-api-db:
    image: mongo
    container_name: comments-api-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - comments-api-data:/data/db
    networks:
      - comments-api-network
    ports:
      - "27017:27017"

volumes:
  Courses-data:
    name: Courses-data
  courses-api-data:
    name: courses-api-data
  comments-api-data:
    name: comments-api-data

networks:
  Courses-network:
    name: Courses-network
  courses-api-network:
    name: courses-api-network
  comments-api-network:
    name: comments-api-network