// <auto-generated />
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Data.Migrations
{
    [DbContext(typeof(CoursesDbContext))]
    [Migration("20241012102033_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the basics of programming using Python.",
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An in-depth study of data structures and algorithms.",
                            Name = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Building dynamic websites using HTML, CSS, and JavaScript.",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Understanding the concepts of databases and SQL.",
                            Name = "Database Management Systems"
                        },
                        new
                        {
                            Id = 5,
                            Description = "An introduction to machine learning concepts and techniques.",
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Principles and practices of software engineering.",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Creating applications for iOS and Android platforms.",
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Basics of protecting systems and networks from cyber threats.",
                            Name = "Cybersecurity Fundamentals"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Exploring cloud services and deployment models.",
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Designing user-friendly interfaces and experiences.",
                            Name = "User Experience Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
